$primary_paletteKeyColor = 9900fd
$secondary_paletteKeyColor = 8a6e8e
$tertiary_paletteKeyColor = 98678e
$neutral_paletteKeyColor = 7d7481
$neutral_variant_paletteKeyColor = 7e7484
$background = 17111b
$onBackground = eadfed
$surface = 17111b
$surfaceDim = 17111b
$surfaceBright = 3d3742
$surfaceContainerLowest = 110c16
$surfaceContainerLow = 1f1923
$surfaceContainer = 231d28
$surfaceContainerHigh = 2e2832
$surfaceContainerHighest = 39323d
$onSurface = eadfed
$surfaceVariant = 4c4452
$onSurfaceVariant = cfc2d4
$inverseSurface = eadfed
$inverseOnSurface = 342e39
$outline = 988d9d
$outlineVariant = 4c4452
$shadow = 000000
$scrim = 000000
$surfaceTint = deb7ff
$primary = deb7ff
$onPrimary = 4a007f
$primaryContainer = 6a00b1
$onPrimaryContainer = f1dbff
$inversePrimary = 8b00e7
$secondary = ddbce0
$onSecondary = 3f2844
$secondaryContainer = 573e5c
$onSecondaryContainer = fad8fd
$tertiary = eeb5e0
$onTertiary = 4a2244
$tertiaryContainer = b480a9
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = f1dbff
$primaryFixedDim = deb7ff
$onPrimaryFixed = 2d0050
$onPrimaryFixedVariant = 6a00b1
$secondaryFixed = fad8fd
$secondaryFixedDim = ddbce0
$onSecondaryFixed = 28132e
$onSecondaryFixedVariant = 573e5c
$tertiaryFixed = ffd7f3
$tertiaryFixedDim = eeb5e0
$onTertiaryFixed = 320c2e
$onTertiaryFixedVariant = 63385c
$term0 = 353434
$term1 = df4ffc
$term2 = ffbac2
$term3 = ffdcf2
$term4 = aaa5d7
$term5 = cb98dd
$term6 = 9dceff
$term7 = e8d3de
$term8 = ad9fa8
$term9 = ed7cff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = babfdd
$term13 = ddafe9
$term14 = bae0ff
$term15 = ffffff
$rosewater = fbeef6
$flamingo = f0dcef
$pink = f2d2ff
$mauve = d9afff
$red = db9ded
$maroon = dbb0e2
$peach = f1bdec
$yellow = ffecf3
$green = c8e3ff
$teal = dedcff
$sky = ddd6ff
$sapphire = ccbfff
$blue = cab0ff
$lavender = dbc2ff
$klink = 8f7acd
$klinkSelection = 907acd
$kvisited = a068cb
$kvisitedSelection = a068cb
$knegative = c559e1
$knegativeSelection = c559e0
$kneutral = f37ef5
$kneutralSelection = f37df5
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = eadfed
$subtext1 = cfc2d4
$subtext0 = 988d9d
$overlay2 = 857a8a
$overlay1 = 716776
$overlay0 = 5f5664
$surface2 = 4e4552
$surface1 = 3c3541
$surface0 = 29232e
$base = 17111b
$mantle = 17111b
$crust = 16101a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
