#!/usr/bin/env bash

source ~/scripts/spinner.sh

run_with_spinner "Updating Dotfiles" -- git -C ~/dots/ pull

if [ -n "$1" ]; then
  export FILE="/etc/nixos/$1.nix"
else
  export FILE="/etc/nixos/$(ls /etc/nixos | fzf)"
fi
sudo -E $EDITOR $FILE
echo $FILE
git -C ~/dots/ diff
sleep 1
run_with_spinner "Updating System" -- sudo -E nixos-rebuild switch
if (($? == 0)); then
  git -C ~/dots/ add ~/dots/*
  git -C ~/dots/ commit -a
  git -C ~/dots/ push
else
  echo "Error: Couldn't Rebuild System, will not Commit"
fi
