general {
    lock_cmd = pidof hyprlock || hyprlock --grace 10
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# DIM (Saves current level, then dims, using exponential -10%)
listener {
    timeout = 60
    on-timeout = brightnessctl -se set 10%- # -s saves current level
    on-resume = brightnessctl -r                # -r restores saved level
}
# Lock the screen with a grace of 10 seconds
listener {
    timeout = 70 
    on-timeout = loginctl lock-session
}
# turn off screen
listener {
    timeout = 75
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
