theme {
    # The full path to a color scheme. Can be a qt6ct theme, or a KColorScheme.
    # Leave empty for defaults.
    color_scheme = "/home/liforra/.local/share/color-schemes/ShadesOfPurple.colors"

    # Name of an icon theme to use.
    icon_theme = "breeze-dark"

    # Widget style to use, e.g. Fusion or kvantum-dark.
    style = "Fusion"

    # Font family for the regular font.
    font = "Sans Serif"

    # Font size for the regular font.
    font_size = 10

    # Font family for the fixed width font.
    font_fixed = "Monospace"

    # Font size for the fixed width font.
    font_fixed_size = 10
}
